version: "3.9"
services:
  # apiのコンテナ
  api:
    container_name: api
    build: ./api
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/workspace:cached

  # webのコンテナ
  web:
    container_name: web
    build:
      # baseコンテナを使用する(Dockerfile)
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
