name: Deploy Simple CI/CD

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-1
  ECS_SERVICE: simple-cicd-service
  ECS_CLUSTER: simple-cicd-cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json

permissions:
  contents: read

jobs:
  # Web container Build/Test
  ## Get Source
  web-test-build-image:
    name: Web Container - Test and Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      ## Build Test
      - name: Build an Image and Run Tests
        ## docker Image build
        run: docker image build --target production -t temp_web_image_name:latest --build-arg REACT_APP_API_SERVER=/api .

      ## Login AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## Push image to ECR
      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_WEB_SERVER_REPOSITORY }}
        run:
          # pushの際に、image名をリポジトリ名にする必要あり
          docker image tag temp_web_image_name:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTORY/$ECR_REPOSITORY:latest

  # API container Build/Test
  ## Get Source
  api-test-build-image:
    name: API Container - Test and Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3

      ## Build Test
      - name: Build an Image and Run Tests
        ## docker Image build
        run: docker image build --target production -t temp_api_image_name:latest .

      ## Login AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## Push image to ECR
      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_API_SERVER_REPOSITORY }}
        run:
          # pushの際に、image名をリポジトリ名にする必要あり
          docker image tag temp_web_image_name:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTORY/$ECR_REPOSITORY:latest

  # Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    # 上記2つのジョブが終わっていること
    needs: [web-test-build-image, api-test-build-image]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ## Login AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # web container のイメージIDを最新に取り込む
      - name: Fill in the new image ID in the Amazon ECS task definition for web
        id: render-web-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: web
          image: ${{ steps.login-ecr.outputs.registory }}/${{ secrets.AWS_ECR_WEB_SERVER_REPOSITORY }}

      # api container のイメージIDを最新に取り込む
      - name: Fill in the new image ID in the Amazon ECS task definition for api
        id: render-api-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: web
          image: ${{ steps.login-ecr.outputs.registory }}/${{ secrets.AWS_ECR_API_SERVER_REPOSITORY }}

      # Edit Task Definition
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-api-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
